#ifndef EXTRAGUIQTLIB_GLOBAL_H
#define EXTRAGUIQTLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EXTRAGUIQTLIB_LIBRARY)
#  define EXTRAGUIQTLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EXTRAGUIQTLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EXTRAGUIQTLIB_GLOBAL_H
